url: "https://share-up.pt" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "ShARE-UP" # the name of your site, e.g. ACME Corp.


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/share_uporto/
  - title: facebook
    url: http://facebook.com/SHAREUniversityPorto/




# Postal address (add as many lines as necessary)
address:
  - line: 3481 FEUP
  - line: Porto, Portugal


#copyright
copyright_description: Designed by
copyright_name: Diogo Valente
copyright_url: https://www.linkedin.com/in/diogovalentepolonia/


# Build settings
markdown: kramdown
permalink: pretty


collections_dir: my_collections
collections:  
  board:
  members:



#networks
networks:
- name: Energy
  img: EN
  icon: fas fa-lightbulb
  id: EN
  description: Solar, Wind, Biomass, Renewable Energy, Global Agencies & International Policies, Nuclear, CO2 Emission, Grid, Transmission & Distribution, Coal Energy, Environment, Hydropower
  nm-name: Diogo Valente
  nm-img: DiogoPolonia.png
  nm-quote: "Do not put off till tomorrow what you can do after tomorrow"
  nm-description:
  nm-linkedin: https://www.linkedin.com/in/diogovalentepolonia/
- name: Industry
  img: IND
  icon: fas fa-industry
  id: IND
  description: Logistics & Supply Chain, Lean Management, Manufacturing Processes, Quality Management, Heavy Industry, Industrial Policies, Machinery, Infrastructure
  nm-name: Beatriz Gomes
  nm-img: BeatrizGomes.png
  nm-quote: "Life is short. Smile while you still have teeth"
  nm-description:
  nm-linkedin:  https://www.linkedin.com/in/beatriz-gomes-5b7019171
- name: Business Strategy
  img: BS
  icon: fas fa-briefcase
  id: BS
  description: Marketing, Mergers & Acquisition , Human Resources , Strategy & Planning , Expansion, Organisation , Operational Effectiveness , Pricing
  nm-img: JoaoNeves.png
  nm-name: João Neves
  nm-quote: "If anything is possible is it possible for something to be impossible?"
  nm-description:
  nm-linkedin: https://www.linkedin.com/in/jo%C3%A3o-neves-881005187/
- name: Global Economics
  img: GE
  icon: fas fa-euro-sign
  id: GE
  description: Poverty Lines & HDI, Agriculture & Development, Economic Growth, Inequality, Unemployment, Disability, Youth, Elders, Happiness, Social Business, Macroeconomic models, Macroeconomic Crisis, Public Economics, Education, Trade, Monetary Policies, Fiscal Policies, Globalization & Development, Microfinance, Health
  nm-img: SaraCosta.png
  nm-name: Sara Costa
  nm-quote: "Rule n. 1, there are no rules. Rule n. 2, see above"
  nm-description:
  nm-linkedin: https://www.linkedin.com/in/sara-costa-685356195/
- name: ICT & Innovation
  img: ICT
  icon: fas fa-mouse-pointer
  id: ICT
  description: Telecom Networks, IT Industry , Software Industry , Internet Industry , Rural ICT, Social Networks, Telecom Vendors , Venture Capital & Innovation Funds , R&D Models , Social Entrepreneurship , Government Policies, Intellectual Property Rights, Entrepreneurs Sociology , Scientific Parks & Incubators , Universities
  nm-img: MargaridaSa.png
  nm-name: Margarida Sá
  nm-quote: "I'm not moody, I just haven't drank coffee today"
  nm-description:
  nm-linkedin: https://www.linkedin.com/in/margarida-pinto-sá/
- name: Mobility
  img: MOB
  icon: fas fa-paper-plane
  id: MOB
  description: Urban Logistics, Sustainable Logistics, Electric Mobility, Autonomous Driving, Public Transit, Mobility Policies, Walking and cycling, Shared Mobility, Traffic management, Infrastructure,Safety
  nm-img: VictorPetisco.png
  nm-name: Victor Petisco
  nm-quote: "Bad decisions make good stories"
  nm-description:
  nm-linkedin: https://www.linkedin.com/in/victor-v-petisco-5baa83163