url: "https://share-up.pt" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "ShARE-UP" # the name of your site, e.g. ACME Corp.


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/share_uporto/
  - title: facebook
    url: http://facebook.com/SHAREUniversityPorto/




# Postal address (add as many lines as necessary)
address:
  - line: 3481 FEUP
  - line: Porto, Portugal


#copyright
copyright_description: Designed by
copyright_name: Diogo Valente
copyright_url: https://www.linkedin.com/in/diogovalentepolonia/


# Build settings
markdown: kramdown
permalink: pretty


collections:
  board:



#networks
networks:
- name: Energy
  img: EN
  icon: fas fa-lightbulb
  id: energy
  description: Solar, Wind, Biomass, Renewable Energy, Global Agencies & International Policies, Nuclear, CO2 Emission, Grid, Transmission & Distribution, Coal Energy, Environment, Hydropower
- name: Industry
  img: IND
  icon: fas fa-industry
  id: industry
  description: Logistics & Supply Chain, Lean Management, Manufacturing Processes, Quality Management, Heavy Industry, Industrial Policies, Machinery, Infrastructure
- name: Business Strategy
  img: BS
  icon: fas fa-briefcase
  id: business
  description: Marketing, Mergers & Acquisition , Human Resources , Strategy & Planning , Expansion, Organisation , Operational Effectiveness , Pricing
- name: Global Economics
  img: GE
  icon: fas fa-euro-sign
  id: economics
  description: Poverty Lines & HDI, Agriculture & Development, Economic Growth, Inequality, Unemployment, Disability, Youth, Elders, Happiness, Social Business, Macroeconomic models, Macroeconomic Crisis, Public Economics, Education, Trade, Monetary Policies, Fiscal Policies, Globalization & Development, Microfinance, Health
- name: ICT
  img: ICT
  icon: fas fa-mouse-pointer
  id: ict
  description: Telecom Networks, IT Industry , Software Industry , Internet Industry , Rural ICT, Social Networks, Telecom Vendors , Venture Capital & Innovation Funds , R&D Models , Social Entrepreneurship , Government Policies, Intellectual Property Rights, Entrepreneurs Sociology , Scientific Parks & Incubators , Universities
- name: Mobility
  img: MOB
  icon: fas fa-paper-plane
  id: mobility
  description: Urban Logistics, Sustainable Logistics, Electric Mobility, Autonomous Driving, Public Transit, Mobility Policies, Walking and cycling, Shared Mobility, Traffic management, Infrastructure,Safety